#!/usr/bin/python3

import token
import slr
import sys
import stack

# file_name = sys.argv[1]
file_name = 'sample.txt'
open_file = open(file_name, 'r')
#result_file = open("{}_result.txt".format(file_name), 'w')

input_text = open_file.readlines()
input_buffer = []

for i in input_text:
    j = 0
    while i[j] != ' ':
        j += 1

    input_buffer.append(i[:j].lower())

